routes_doc.md

make a doc for members routes.

project routes doc

---

client/src/App.js
client/src/components/common components/search/index.jsx
client/src/components/common components/search/style.css

make a search component with its style.

Search component

---

client/src/App.js
client/src/components/Layout/Header/index.jsx
client/src/components/Layout/Header/style.css

Make the header component and styled it.

Header component

---

client/package-lock.json
client/package.json
client/src/App.js
package-lock.json
package.json

added antDesign library and import its style file to use it.

antDesign Library 

---

client/package-lock.json
client/package.json

install prop-types

---

client/src/components/Projects/index.jsx
client/src/components/Projects/projectsTable/index.jsx
client/src/components/Projects/projectsTable/style.css
client/src/components/Projects/style.css
client/src/components/utils/projects.js

create projects page that contains projects Table and button component in addition to search component.
projects table will view projects data and allow user to edit/delete/new specific project.
relates #17

Projects page

---

package.json

add a script for kill ports for react and express
Relates #83

add script for kill ports 

---

client/src/components/Projects/ProjectNew/style.css

fix out-line and padding for inputs

---

client/src/components/Layout/Header/index.jsx
client/src/components/Layout/Header/style.css

Relates #27
1. Replace div with header element. 
2. Replace the user menu with antd Dropdown component. It is nicer and responsive.
3. Replace anchors with react-dom-router Navlink components for navigation links: projects & users.
4. Edit the state to include: username and role. This might change when we handle authentication.
5. Change some elements' classnames
6. Update the style replacing floats with flex. It is more responsive.

Edit  header

---

client/src/components/Projects/index.jsx
client/src/components/Projects/style.css

improve +project button link, now you can click on + or project to route to new project page
relates #17

improvement

---

client/src/components/commonComponents/search/index.jsx

Remove enterButton from SearchFor component coz no need for it
relates #80

remove enterButton from SearchFor component coz no need for it

---

client/src/App.js
client/src/components/PageNotFound/index.jsx

- edit app file to add login component and 
- NotFoundPage to the component folder and in-app file
Relates #29 and #63

add NotFoundPage and login in app file

---

client/src/components/Projects/ProjectEdit/index.jsx

fix the title of the page from create to Edit

fix the title of page

---

client/src/components/Layout/Header/style.css
client/src/components/PageNotFound/style.css
client/src/components/Projects/ProjectEdit/style.css
client/src/components/Projects/ProjectNew/style.css
client/src/components/Projects/style.css

Edit z-index to 3 to be over every thing in the page

---

server/database/config/connection.js
server/database/config/dbBuild.sql

modify sql build file

---

server/database/config/dbBuildFakeData.sql
server/database/config/insertFakeData.js

Schema fake data

---

package.json
server/database/config/connection.js
server/database/queries/selectProjectDetails.js
server/database/queries/selectProjects.js
server/database/queries/selectScrumTasks.js
test/index.js
test/server/projectDetailsQuery.test.js
test/server/projectsQuery.test.js
test/server/scrumTasks.test.js
test/server/test.js

Scrum tasks query

---

server/database/config/connection.js
server/database/queries/selectProjectDetails.js
test/server/projectDetailsQuery.test.js

Project details query

---

server/database/queries/selectProjectScrums.js
test/index.js
test/server/projectScrums.js

#111  made a query for select scrums of a project and tested it.

Select scrums project

---

server/database/config/dbBuild.js

add a condition to rebuild sql

---

server/app.js
server/controllers/index.js
server/controllers/projects/deleteProject.js
server/controllers/projects/getProject.js
server/controllers/projects/getProjects.js
server/controllers/projects/index.js
server/controllers/projects/post.js
server/controllers/projects/put.js
server/controllers/scrums/deleteScrum.js
server/controllers/scrums/getScrums.js
server/controllers/scrums/getTasks.js
server/controllers/scrums/index.js
server/controllers/scrums/post.js
server/controllers/scrums/put.js
server/controllers/tasks/deleteTask.js
server/controllers/tasks/index.js
server/controllers/tasks/post.js
server/controllers/tasks/put.js
server/controllers/users/deleteUser.js
server/controllers/users/get.js
server/controllers/users/index.js
server/controllers/users/post.js
server/controllers/users/put.js
server/index.js

Controllers

---

test/server/projectScrums.js

edit selectProjectScrums test

---

package-lock.json
package.json
test/index.js

Install happi joi

---

server/database/config/dbBuild.sql
test/index.js

add on delete cascade on scrums and tasks tables

---

server/database/queries/insertTask.js
test/index.js
test/server/insertNewTask.js

#138  
- new file for ```insertTask``` query func.
- made  ```insertTask```
- testing for it.

Insert task query

---

server/database/config/insertFakeData.js

fix inserFakeData bug

---

.travis.yml
package.json
server/database/config/insertFakeData.js
test/index.js

set database in travis and add a script for test locally

---

server/controllers/scrums/helpers/validateNewScrum.js
server/controllers/scrums/index.js
server/controllers/scrums/post.js
server/database/queries/insertScrum.js
test/index.js
test/server/insertScrumQuery.js
test/server/routes/postScrumRoute.js

Post scrum route

---

server/controllers/projects/post.js
server/controllers/projects/put.js
server/database/config/insertFakeData.js
server/database/queries/updateProject.js
test/index.js
test/server/routes/projectEditRoute.test.js
test/server/routes/projectNewRoute.test.js

Project edit route

---

test/server/routes/projectEditRoute.test.js

fix bug in test

---

client/package-lock.json
client/package.json
package-lock.json
package.json

Install axios

---

client/src/App.js
client/src/auth/index.jsx
client/src/auth/isAuth.js
client/src/components/Layout/Header/index.jsx
client/src/components/Login/index.jsx
client/src/components/Login/loginForm/index.jsx

Front end auth

---

server/controllers/index.js
server/controllers/middleware/authentication.js
server/controllers/middleware/helpers.js

add middleware for auth to check cookie

---

server/controllers/index.js
server/controllers/logout/index.js

add logout route

---

server/controllers/users/post.js

Bug post controller

---

server/controllers/login/login.js

added the payload to the response.

send the payload with res

---

server/controllers/index.js
server/controllers/isAuth/index.js

Backend authentication route

---

package.json

add two scripts for heroku deploy

---

server/controllers/projects/getScrums.js
server/controllers/projects/index.js
server/controllers/projects/post.js
server/controllers/projects/put.js
server/database/queries/selectProjects.js

Backend refactor

---

client/src/App.js
client/src/auth/index.jsx
client/src/auth/isAuth.js
client/src/components/Login/loginForm/index.jsx
client/src/components/Project/index.jsx
client/src/components/Projects/ProjectEdit/index.jsx
client/src/components/Projects/ProjectNew/index.jsx
client/src/components/Projects/index.jsx
client/src/components/commonComponents/TableMember/index.jsx

Front-end requests for project(s):
relates #184

Front end requests Projects

---

server/controllers/tasks/deleteTask.js
server/database/queries/deleteTask.js
test/index.js
test/server/routes/deleteTaskRoute.js

TASK | DELETE

---

client/src/App.js
client/src/auth/isAuth.js

resolve login issue: when we refresh the page  login is lost

Resolve login

---

client/src/components/Layout/Header/index.jsx
client/src/components/Users/form/index.jsx

Users refactor

---

server/database/config/dbBuild.sql

add on delete cascade for users-projects table

---

client/src/components/Project/Scrums/index.jsx

add delete task functionality

---

server/controllers/projects/getProject.js
server/controllers/projects/post.js
server/controllers/tasks/index.js
server/controllers/tasks/post.js
server/database/config/insertFakeData.js
server/database/queries/selectProjectDetails.js
server/database/queries/selectUsers.js
test/server/insertNewTask.js
test/server/projectDetailsQuery.test.js
test/server/routes/getProjectRoute.js
test/server/routes/getScrumRoute.js
test/server/routes/insertTaskRoute.js
test/server/routes/projectNewRoute.test.js
test/server/scrumTasks.test.js

#219 
- Fix bugs in queries:
- InsertTask (assgined_to is the user's full_name, not id)
- selectProjectDetails: I made inner join with users table to select full_name. @aminalakhsham, check my comments below.
- Fix bugs in tests

Fix travis

---

client/src/components/Projects/ProjectEdit/index.jsx
client/src/components/commonComponents/TableMember/index.jsx
test/index.js

resolve edit projects problem

---

server/controllers/login/login.js
server/controllers/middleware/authentication.js
server/controllers/middleware/error.js
server/controllers/projects/deleteProject.js
server/controllers/projects/getProject.js
server/controllers/projects/getProjects.js
server/controllers/projects/getScrums.js
server/controllers/projects/post.js
server/controllers/projects/put.js
server/controllers/scrums/getTasks.js
server/controllers/scrums/helpers/validateNewScrum.js
server/controllers/scrums/post.js
server/controllers/scrums/put.js
server/controllers/tasks/post.js
server/controllers/users/helpers/validateUser.js
server/controllers/users/post.js
server/controllers/users/updatePassword.js

Relates #218
**Refactor error object to be able to console the error message during development stage**
- When the error is thrown in the catch, I only edit the code as required and then pass it to next(). For example,
```javascript
.catch((error) => {
error.code = 401;
next(error);
});
```
- When the error is within `then`, I create an error object and pass it to next(). For example, if checkUser() returns no row in login (POST), I pass the error this way,
```javascript
if(result.rows[0]){
next({code: 401, msg: 'username doesnt exist' })
}
```

refactor error object in controllers files

---

client/src/components/Users/form/index.jsx

#224 
- fix bug: 
- display `'password length should be greater than 6` msg when pass less than 6char instead of `passwords don't match`

Pass validation (fix bug)

---

client/src/components/Project/Scrum/index.jsx

#237 
- Complete deleteScrum Function
- Redirect to previous or next scrum after deletion
- Fix bugs in componentDidUpdate

Delete scrum bug

---

client/src/components/Project/Scrum/index.jsx

Add scrum bug

---

client/src/components/Project/Scrum/TaskTable/index.jsx
client/src/components/Project/Scrum/index.jsx

Edit scrum name bugs

---

client/src/components/Projects/ProjectEdit/index.jsx
client/src/components/commonComponents/TableMember/index.jsx

solve TableMember appearance problem

---

client/src/components/Project/Scrum/TaskTable/index.jsx
client/src/components/Project/Scrum/utilis/filter.js
client/src/components/Project/Scrum/utilis/helpers.js
client/src/components/Project/Scrum/utilis/sort.js

Refactor tasks

---

client/src/components/Projects/ProjectNew/index.jsx
client/src/components/Projects/index.jsx

- Remove project id from projects table.
- Remove console.log from new project page.
relates #229

Refactor project table

---

client/src/components/Project/Scrum/TaskTable/index.jsx
client/src/components/Project/Scrum/utilis/helpers.js
server/database/queries/insertTask.js

finish add new task and fix bugs

---

client/src/components/Project/Scrum/utilis/helpers.js
server/controllers/tasks/put.js
server/database/queries/updateTask.js

Edit task bug

---

client/src/components/Users/index.jsx

add functionality to change password in adding new user.
relates #226

add change password action

---

client/src/components/Project/Scrum/TaskTable/index.jsx
client/src/components/Project/Scrum/utilis/helpers.js

Fix delete bug

---

client/src/components/Users/index.jsx

fix bug on html prop in editableContent component in user table

---

client/src/components/Layout/Header/index.jsx

resolve logout click area

---

client/src/components/Project/Scrum/TaskTable/index.jsx
client/src/components/Project/Scrum/select/index.jsx

edit defaultVaLue and filter

---

client/src/components/Project/Scrum/utilis/helpers.js

edit validation for tasks

---

client/src/components/Project/Scrum/index.jsx
client/src/components/Project/style.css

remove white hover & resolve edit scrum name bug

---

client/src/components/Project/index.jsx

fix bug in redirection

---

client/src/components/Project/Scrum/TaskTable/TaskColumns.jsx
client/src/components/Project/Scrum/TaskTable/index.jsx
client/src/components/Project/index.jsx
server/database/config/dbBuild.sql

refactor tasks table

---

client/src/components/Projects/ProjectEdit/index.jsx

reslove null description entered

---

client/src/components/Project/Scrum/TaskTable/TaskColumns.jsx
client/src/components/Project/Scrum/TaskTable/index.jsx
client/src/components/Project/Scrum/utilis/helpers.js
client/src/components/Users/form/index.jsx
client/src/components/Users/index.jsx

I add it for the UsersPage
I think we need to add the focus to the tasks also!? @IsraaSulaiman 
#227

fix: add focus to the new row

---

client/src/components/Project/Scrum/index.jsx
client/src/components/Project/Scrum/utilis/scrumHelpers.js
client/src/components/Users/notification/index.jsx

- use onBlur instead of onChange
- add notification for task renaming

Task refactor
